### ISSUE TITLE
proposal: provide a mixin class for an `is_evented` attribute

### ISSUE THREAD

**Issue by alisterburt** [tlambert03/psygnal#20]
I'm porting the 'bubbling up' of events on the psygnal backed evented list and would benefit from something similar to the [napari event system mixin](https://github.com/napari/napari/blob/main/napari/utils/events/types.py) in psygnal.

Specifically, when porting
https://github.com/napari/napari/blob/77426246caa9db492fbd0645d78be02e4aa4024b/napari/utils/events/containers/_evented_list.py#L198-L204
I realised there is no easy way to check whether an object has attributes which are `Signal`s without explicitly iterating over the object and checking which sounds... not ideal

How do you feel about a simple mixin class in `psygnal` called `EventedMixin` which provides a boolean `is_evented` attribute as a 'standard' way to declare that an object is evented providing an easy way to check it?

**Comment by tlambert03** [comment]
hmm, good point. an additional issue here is that psygnal doesn't have the same concept of an EmitterGroup at all... (where connecting to one thing connects you to everything).  That would also be necessary for that "connect child emitters" trick there... but I'm not immediately sure how that should look here

**Comment by tlambert03** [comment]
having another looks at this, the whole thing thing with `EventedList` becomes more complicated when you can't assume that every emitter is emitting the exact same type (a single Event object).  We might need to special case the [`_reemit_child_event`](https://github.com/napari/napari/blob/77426246caa9db492fbd0645d78be02e4aa4024b/napari/utils/events/containers/_evented_list.py#L182) there.  

Getting back to the original point, I'm not sure I love the idea of an `EventedMixin` exported from psygnal.  That seems like something that should be structurally typed by the end-user typed a `Protocol` as I did with [`SupportsEvents`](https://github.com/napari/napari/blob/main/napari/utils/events/types.py)... even there, we're just cementing an in-library convention (having an emitter group with a name `events` is not intrinsic to that event system... just our convention).  So I think here I'd recommend:

```python
from psygnal import Signal

class EventGroup:
    a = Signal(int)
    b = Signal(str)
    c = Signal()

class Thing:
    def __init__(self):
        self.events = EventGroup()
```

and then... one of the major differences (and indeed motivating factors) here is that events are less dynamic.  Whereas EmitterGroup is just a dict of emitters that you can iterate, here signals are class attributes... so I actually think to your original point:

> there is no easy way to check whether an object has attributes which are Signals without explicitly iterating over the object and checking which sounds... not ideal

yes... but in this design there really won't be dynamically added signals.  Just like in Qt, an object has it's set of signals that it emits, and you _know_ what they are.  inspection with `dir` is fine if you need to as well... but it shouldn't need to happen more than once per session.

**Comment by tlambert03** [comment]
I can't say I've really thought about it enough to have a strong opinion.  .events doesn't feel as Qt-like (not that we need to stick to that or anything), but it does have the advantage of minimizing namespace pollution. I'd say if either one presents a clear advantage, go with it, otherwise I'm not sure yet :)
