### ISSUE TITLE
Idea: Allow conect setting attribute to Signal

### ISSUE THREAD

**Issue by Czaki** [tlambert03/psygnal#36]
As psygnal comes from Qt which is a C++ world that does not contain the equivalent of `@property` or descriptors. Using property is quite popular in python projects, but connected with signals could produce a big amount of redundant code. 

So maybe it could be a nice idea to allow connect a property to signal. 

```python
def property_weakref(obj: Union[weakref.ref, object], name:str) -> Tuple[weakref.ref, Callable]:
    if not isinstance(obj, weakref.ref):
        obj = weakref.ref(obj)
    def wrap(*args: Any) -> None:
        if len(args) == 1:
            setattr(obj(), name, args[0])
        else:
            setattr(obj(), name, args)

    return (obj, wrap)
```

and a proper modification for the `connect` function which allows providing tuple `(obj, str)` as input.

**Comment by tlambert03** [comment]
love it.  dealing with setter callbacks is one of the most annoying things about using `property.setter`... would be great to make that case seamless

**Comment by tlambert03** [comment]
(can't decide if i think it should be a new `connect` method though:

```py
emitter.connect_attr(obj, 'attr_name')
```

do you want to implement this?  Or just happy to see it get added?
