### ISSUE TITLE
Add an object with `blockSignals`

### ISSUE THREAD

**Issue by ianhi** [tlambert03/psygnal#72]
### Description
`psygnal` adds the very nice ability to block individual signals. However, with Qt signals the only way to block a signal is to call `blockSignals` on a `QOjbect`. Ideally I'd be able to have  an object from psygnal that would also provide `blockSignals` so users who are interacting with either a QObject of psygnal don't need to perform any checks.

This is specifically inspired by these lines:
https://github.com/tlambert03/pymmcore-plus/blob/ea3f460414232f513c6156c7cf8e3f61f3097e96/pymmcore_plus/core/_mmcore_plus.py#L107-L108

**Comment by tlambert03** [comment]
not totally sure I'm following the desired outcome.  We could perhaps add a utility like [the one used in napari](https://github.com/napari/napari/blob/40c4e911b487234a8f66aa74d735514b38016664/napari/_qt/utils.py#L123) to superqt, but i can't quite see where in psygnal we should be trying to block qt-based signals.  Can you give a toy example of what you'd want to be blocking?

**Comment by ianhi** [comment]
Sorry i was unclear. I mean that unless I make a QObject I won't be able to use that superqt `blockSignals`. The issue with this:

```python
   with self.events.propertyChanged.blocked():  # block the native event.
            super().setProperty(label, propName, propValue)
```

was that `events` could be either a python object with `psygnal` signals, in which case it worked. Or it could be a QObject with qt Signals, in which case the correct thing to do would be to do `with superqt.blockSignals(self.events):` and that line actually breaks. So I was imagining some object like:

```python
class signaler
    def blockSignals(self, blocked: bool):
       # in here knows how to check for all signals on this object and block them one by one
        ...
```

that way when using psygnal the `events` objects can inherit from `signaler` and get the same behavior wrt signals as if we inherited from QObject.

I suppose ideally there wouldn't be a need to have an object that is maybe a QObject and maybe not, but that would depend on https://github.com/tlambert03/psygnal/issues/73

**Comment by tlambert03** [comment]
> I mean that unless I make a QObject I won't be able to use that superqt blockSignals

ahhh I see.  ok, in that case, we should review the code for places where we've assumed a given signal interface.  If that's the only place, then let's just deal with it there:

```
from psygnal import SignalInstance
from superqt.utils import signals_blocked
from functools import partial

if isinstance(self.events.propertyChanged, SignalInstance)
    event_blocker = self.events.propertyChanged.blocked
else:
    event_blocker = partial(signals_blocked, self.events.propertyChanged)

with event_blocker():
    super().setProperty(label, propName, propValue)
```

**Comment by tlambert03** [comment]
or make a utility function:

```py
def event_blocker(obj):
    if isinstance(obj, SignalInstance)
        return obj.blocked
    else:
        return partial(signals_blocked, obj)

with event_blocker(self.events.propertyChanged):
    super().setProperty(label, propName, propValue)
```

**Comment by ianhi** [comment]
> ahhh I see. ok, in that case, we should review the code for places where we've assumed a given signal interface. If that's the only place, then let's just deal with it there:

Yeah, that's the only place I'm aware of. Just wasn't sure if this would be a generalizable problem. Though on reflection it's probably not. I suppose the purpose of this library is you like qt style signals, but don't want to use qt, and pymmc+ breaks that assumption because sometimes it also wants to use qt signals.

**Comment by ianhi** [comment]
Sounds good!
